### ISSUE TITLE
Организовать запуск на Heroku

### ISSUE THREAD

**Issue by qertis** [gotois/ProstoDiary_bot#540]
- [x] 2020-04-09T07:24:38.823319+00:00 app[web.1]: Error: Cannot find module 'supertest'
2020-04-09T07:24:38.823320+00:00 app[web.1]: Require stack:
2020-04-09T07:24:38.823320+00:00 app[web.1]: - /app/src/services/request.service.js
2020-04-09T07:24:38.823321+00:00 app[web.1]: - /app/src/app/controllers/web/oidc.js
2020-04-09T07:24:38.823321+00:00 app[web.1]: - /app/src/app/routes/main.js
2020-04-09T07:24:38.823321+00:00 app[web.1]: - /app/src/app/server.js

- [x] 2020-04-09T10:34:11.999579+00:00 app[web.1]: NotFoundError: Resource not found.
2020-04-09T10:34:11.999580+00:00 app[web.1]:     at many (/app/node_modules/slonik/dist/connectionMethods/many.js:31:11)
2020-04-09T10:34:11.999581+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-04-09T10:34:11.999581+00:00 app[web.1]:     at async /app/src/lib/oidc.js:24:27
2020-04-09T10:34:11.999582+00:00 app[web.1]:     at async createConnection (/app/node_modules/slonik/dist/factories/createConnection.js:118:14)
2020-04-09T10:34:11.999582+00:00 app[web.1]:     at async module.exports (/app/src/lib/oidc.js:23:19)
2020-04-09T10:34:11.999583+00:00 app[web.1]:     at async main (/app/src/app/server.js:26:24)
2020-04-09T10:35:06.272587+00:00 app[web.1]: Error waiting for process to terminate: No child processes

**Comment by qertis** [comment]
Нужно сообразить как добавлять ассистентов на Heroku сервер
